services:
- type: web
  name: nodeRender
  plan: free
  runtime: node
  region: frankfurt
  branch: main
  buildCommand: npm install
  startCommand: npm run start
  repo: https://github.com/Spykoninho/nodeRenderCloud
  envVars:
  - key: DB_CONNECTION_STRING
    fromDatabase:
      name: nodeRenderDB
      property: connectionString
databases:
- name: nodeRenderDB
  region: frankfurt
  plan: free